### ISSUE TITLE
User Authentication 

### ISSUE THREAD

**Issue by jli57** [jli57/lifenovel#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by jli57** [comment]
Hi Cynthia, I'm done with the User Authentication MVP. Please take a look and let me know your thoughts. Thanks!

**Comment by xnanodax** [comment]
Looks good!! Great frontend validation w/ the icons and custom message per input field on the sign up form!

- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect to either `/`, `/login`, or `/signup`
- [x] When logged in, users shouldn't be able to access `/login` or `/signup`
![screen shot 2018-10-15 at 10 01 03 am](https://user-images.githubusercontent.com/20424731/46966036-646bed80-d061-11e8-88bf-040dc5187528.png)

**Comment by jli57** [comment]
Protected and Auth Route has been built!
