### ISSUE TITLE
Posts

### ISSUE THREAD

**Issue by jli57** [jli57/lifenovel#3]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds
- [x] Can post on your own wall 
- [x] Can post on friend's wall
- [x] Cannot post on someone's wall you are not friend's with
- [x] Can comment on posts
- [x] Can edit your posts
- [x] Can delete your posts

**Comment by xnanodax** [comment]
Looks good!
