### ISSUE TITLE
Friends

### ISSUE THREAD

**Issue by jli57** [jli57/lifenovel#4]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds
- [x] Can add friends
- [x] Can remove friends
- [x] Can receive friend requests
- [x] Can accept friend requests

**Comment by xnanodax** [comment]
Hey! I was not able to go to another user's show page. I receive a cute "Page is not available" message.

**Comment by xnanodax** [comment]
1) I'm getting a `Page is not available`  for this user: https://lifenovel.herokuapp.com/#/users/21

2) When refreshing a page with a friend (ex: https://lifenovel.herokuapp.com/#/31), there is a slight flicker that the page is unavailable and then it shows up. Consider making a different view whether the friend exist but its still loading vs when the friend doesnt exist at all.

**Comment by jli57** [comment]
Both issues now fixed
